---
title: "Notes_teaching_proj"
format: html
editor: visual
---

# Project description

This repository contains teaching materials associated with my teaching of quantitaive method courses at Lund University. It is mostly datasets, different exercises and at least one shiny app that is used for interactive teaching of basic stats concepts.

## Contents

-   Datasets
-   Exercises and Labs
-   Shiny App
-   Jamovi Explained
-   Usefull links and websites

## Datasets

The idea is to construct a big dataset from EUROSTAT on the NUTS2 level. This allows for enough different variables and different research questions to be used. It is also very easy to access using the 'eurostat' package in R.

Alternative options are below:

-   Historical census data from the US
-   Life expectency (and other data) per US county
-   EU-SILC public use microdata files
-   European Social Survey

### Eurostata variables

-   Population

    -   Population by age and sex

    -   Population growth

    -   One Age Dependncy ratio

    -   Median age of populations

-   Economy

    -   GDP

    -   GDP per capita (calculatied)

    -   R&D expenditure

-   Health

    -   Hospital beds

    -   Life expectancy

-   Labor market

    -   Unemployment rate

    -   hours worker

    -   Employment numbers per sector

    -   employment growth (calculated)

    -   emplyment in High tech sectors

## Shiny App ideas

The app should focus in teaching basic statistical concepts through mostly visual and interactive features:

-   Effect of sample size
-   Visualizing a bar plot
-   Measures of central tendancy
    -   Effect of outliers on the mean
-   Measure of spread
    -   Stepwise calculation of the standard deviation
    -   Relationship between standard deviation and the mean
